### PR TITLE
Feature/add quiz submission

### PR DESCRIPTION
**Pull request by ikubiti**
Completed the process for students taking a quiz. Added and redefined GraphQL resolvers for effective implementation.

### CODE REVIEW

**Review by TheMernMachine — COMMENTED** [review]
Delete unwanted files.

**Review by TheMernMachine — CHANGES_REQUESTED** [review]
Realized you left mock files in your request

**Review by ikubiti — COMMENTED** [review]
Done with deletion of mock files.

**Review by TheMernMachine — APPROVED** [review]
All good

**Pull request merged**
